import  LocalizedStrings from 'react-native-localization';

export default new LocalizedStrings({
    en:{
        Login: 'Login',
        Email: 'Email',
        Password: 'Password',        
        ForgotPassword: 'Forgot Password?',
        Or: 'OR',
        LoginWithOTP: 'Login with OTP',
        LoginWithFacebook: 'Login with Facebook',
        LoginWithGoogle: 'Login with Google',
        DontHaveAccount: "Don't have an account?",
        HaveAccount: "Already have an account?",
        Signup: 'Sign Up',
        Register: 'Register',
        FirstName: 'First name',
        LastName: 'Last name',
        ConfirmPassword: 'Confirm Password',
        Mobileno: 'Mobile Number',
        Submit: 'Submit',
        EmailMobile: 'Email or Mobile number',
        Home: 'Home',
        Myads: 'MyAds',
        Postad: 'PostAd',
        Chat: 'Chat',
        Profile: 'Profile',
        HomeHeader: "Let's join together Let's rise together",
        Search: 'Search',
        Location: 'Location',
        CurrentLocation: 'Current Location',
        //Categories
        Business: 'Business/Inventor',
        Agriculture: 'Agriculture',
        Services: 'Services',
        Gadgets: 'mobile/Gadgets',
        Electronics: 'electrical equipment',
        Automobiles: 'Automobiles',
        Fashion: 'fashion',
        Pets: 'Pets',
        Furniture : 'Furniture/House hold',
        Properties: 'Properties',
        Job: 'Jobs',
        FreeGiveaway: 'Contributions',
        //Subcategories
        Inventor1: "I am an Inventor",        
        Inventor2: "I am looking for an Inventor",
        Inventor3: "I am looking for Investor or business partner",
        Inventor31: "Automobile",
        Inventor32: "Agriculture",
        Inventor33: "Construction & realestate",
        Inventor34: "Courier & movers",
        Inventor35: "Electric & electronic",
        Inventor36: "Energy & Solar ",
        Inventor37: "Furniture ",
        Inventor38: "Hotel & cottage ",
        Inventor39: "Health care",
        Inventor310: "Information technology",
        Inventor311: "Industry & manufacturing ",
        Inventor312: "Restaurants & bakery ",
        Inventor313: "Jewellery ",
        Inventor314: "Textile ",
        Inventor315: "Security device ",
        ViewAll: "View All",
        SubAgriculture1: 'Organic',
        SubAgriculture2: 'Vegetables',
        SubAgriculture3: 'Fruits',
        SubAgriculture4: 'grains/pulses/spices',
        SubAgriculture5: 'value added products',
        SubAgriculture6: 'Animals/fish',
        SubAgriculture7: 'Garden&nursery',
        SubAgriculture8: 'Agriequipment',
        Others: 'Others',
        SubServices1: 'Air conditioner',
        SubServices2: 'Auditor',
        SubServices3: 'Beauty parlor',
        SubServices4: 'Computer & mobiles',
        SubServices5: 'Cook',
        SubServices6: 'Carpenter',
        SubServices7: 'Construction',
        SubServices8: 'Car & bike ',
        SubServices9: 'Electrician',
        SubServices10: 'Event management',
        SubServices11: 'Financial services',
        SubServices12: 'Health care',
        SubServices13: 'Import & Export',
        SubServices14: 'IT',
        SubServices15: 'Laundry',
        SubServices16: 'Lawyer',
        SubServices17: 'Maid',
        SubServices18: 'Movers & Packers ',
        SubServices19: 'Photography',
        SubServices20: 'Plumber',
        SubServices21: 'Security guard',
        SubServices22: 'Travel services',
        SubServices23: 'Taxi',
        SubServices24: 'Wedding consultants',
        SubGadgets1: 'Mobiles',
        SubGadgets2: 'Laptop & PC',
        SubGadgets3: 'Printers & Accessories',
        SubGadgets4: 'Games & Entertainment',
        SubGadgets5: 'Music System & Gadgets',
        SubGadgets6: 'Sparepars',
        SubElectronics1: 'Tv & CCTV systems',
        SubElectronics2: 'Camera',
        SubElectronics3: 'Air Conditioner',
        SubElectronics4: 'Washing Machine & Water Heaters',
        SubElectronics5: 'House Hold Machines',
        SubElectronics6: 'Refrigerator',
        SubElectronics7: 'Kithen Appliances',
        SubAutomobiles1: 'Car',
        SubAutomobiles2: 'Bike',
        SubAutomobiles3: 'Commercial',
        SubFashion1: 'Mens',
        SubFashion2: 'Womens',
        SubFashion3: 'Baby & kids',
        SubPets1: 'Fish & birds',
        SubPets2: 'Dog & cat/other pets ',
        SubPets3: 'Pet food & accessories',
        SubPets4: 'Pets for adoption',
        Subfurniture1: 'Bed & bedsets',
        Subfurniture2: 'Cabinets & dressing table',
        Subfurniture3: 'Sofa set & dining set',
        Subfurniture4: 'Chair & tables',
        Subfurniture5: 'Kids furniture',
        Subfurniture6: 'Tvstand &home decorateitems',
        Subfurniture7: 'Office furniture',
        Subfurniture8: 'Sports Fitness equipment',
        SubProperties1: 'House & Appartment',
        SubProperties2: 'Land',
        SubProperties3: 'Commercial',
        Subjob1: 'Accounting',
        Subjob2: 'Architecture & interior design',
        Subjob3: 'Automobile',
        Subjob4: 'Business development & marketing',
        Subjob5: 'Construction',
        Subjob6: 'Customer services',
        Subjob7: 'Education',
        Subjob8: 'Engineering',
        Subjob9: 'Fashion',
        Subjob10: 'food & beverages',
        Subjob11: 'Graphic design',
        Subjob12: 'Hospital&healthcare',
        Subjob13: 'HR & admin',
        Subjob14: 'Industrial & Manufacturing',
        Subjob15: 'IT',
        Subjob16: 'Legal services',
        Subjob17: 'Logistic & distribution',
        Subjob18: 'Retail & consumer goods',
        Subjob19: 'Safety & security',
        Subjob20: 'sales',
        Subjob21: 'Transportation',
        Subjob22: 'Travel & tourism',
        Subjob23: 'freelancers & part timejobs',
        SubContribution1: 'Free give away',
        SubContribution2: 'Need your help',
        SubContribution3: 'Blood donation',
        SubContribution4: 'Orphanage & Old age homes',
        //Item details
        ItemName: 'Harley Davidson Street Bob dyna',
        ItemName1: 'Pulsar 220',
        ItemLocation: 'SreeKaryam Thiruvananthapuram',
        PublishDate: '29 JUL',
        ItemInfo: '2017 - 23,500 km',
        ItemInfo1: '2014 - 53,000 km',
        //profile
        ViewEdit: 'View & Edit profile',
        Settings: 'Settings',
        Support: 'Support',
        SupportAdmin: 'Connect with admin',
        ChangePassword: 'Change Password',
        Share: 'Share',
        Policy: 'Management Policy',
        Logout: 'Logout',
        Notification: 'Notifications',
        SelectLanguage: 'Select Language',
        Deactivate: 'Delete Account',
        NewPassword: 'New Password',
        ConfirmNewPassword: 'Confirm New Password',
        Favourites: 'Favourites',
        Description: 'Description',
        PostedBy: 'Ad posted by',
        RelatedAds: 'Related Ads',
        Filter: 'Filter',
        CusRating: 'Customer Rating',
        Up: 'Up',
        Related: 'Related',
        Date: 'Date',
        Distance: 'Distance',
        PriceHigh: 'Price: High to Low',
        PriceLow: 'Price: Low to High',        
        SortBy: 'Sort by',
        Price: 'Price',
        Minimum: 'Min',
        Maximum: 'Max',
        Posted: 'Posted by',
        Owner: 'Owner',
        Agent: 'Agent',
        Condition: 'Condition',
        Old: 'Old',
        New: 'New',
        FuelType: 'Fuel Type',
        Petrol: 'Petrol',
        Diesel: 'Diesel',
        LPG: 'LPG',
        Electric: 'Electric',
        Type: 'Type',
        Manual: 'Manual',
        Automatic: 'Automatic',
        Single: 'Single',
        Second: 'Second',
        Third: 'Third +',
        Model: 'Model',
        KM: 'Kilometers',
        Brand: 'Brand Name',
        SelectBrand: 'Select Brand',
        AllModel: 'All Models',
        Bajaj1: 'Bajaj Avenger',
        Bajaj2: 'Bajaj CT 100',
        Bajaj3: 'Bajaj Discover',
        Bajaj4: 'Bajaj Pulsar',
        Bajaj5: 'Bajaj Platina',
        Bajaj6: 'Bajaj Others',
        Clear: 'Clear',
        Submit: 'Submit',
        SelectCategory: 'Select your category',
        Name: 'Title',
        SellerType: 'Seller Type',
        Next: 'Next',
        SelectImage: 'Select image from gallery',
        IncludeDetails: 'Include details',
        UploadImage: 'Upload your photos',
        UploadDetails: 'Submit your details',
        FormError: 'Please complete the form',
        EmailError: 'Please enter valid email address',
        PasswordError: 'Password and Confirm password must be same.',
        ServerError: "Can't get the data from server",
        LogoutMSG: "You have been logout",
        ShowContact: "Press here to show the contact list",
        TotQuantity: "Total Quantity",
        PriceInfo: "Price Information",
        Quantity: "Quantity",
        Salary: 'Salary',
        Role: 'Role',
        Qualification: 'Qualification',
        Experience: 'Experience',
        Company: 'Company name',
        Allowance: 'Allowance',
        License: 'License',
        Vacancy: 'Vacancy',
        PostedBy: 'Posted by',
        Sale: 'Sale',
        Rent: 'Rent',
        PlotSize: 'Plot size',
        Facing: 'Facing',
        BathRoom: 'BathRoom',
        BedRoom: 'BedRoom',
        PropertyType: 'Property Type',
        Finance: 'Finance',
        Update: "Update",
        About: "About myself & Work experience",
        EditProfile: "Edit Profile",
        AboutTab: "About",
        Reviews: "Reviews",
        More: "More",
        Review: "Leave a review",
        Comment: "Your comment",
        PlaceComment: "Tell something about your experience",
        NotificationInfo: "Send and Receive notifications",
        Message: 'Message',
        Privacy: 'Privacy',
        Select: 'Select',
        Tone: 'Tone',
        Kg: "Kg",
        Bag: 'Bag',
        Bunch: 'Bunch',
        Bundle: 'Bundle',
        Pieces: 'Pieces',
        Permanent: 'Permanent',
        Temporary: 'Temporary',
        House: 'House',
        Appartement: 'Appartement',
        Commercial: 'Commercial',
        East: 'East',
        West: 'West',
        North: 'North',
        South: 'South',
        Sqft: 'Sq.Ft',
        Cent: 'Cent',
        Ground: 'Ground',
        Acer: 'Acer',
        Housing: 'Housing Land',
        CommercialLand: 'Commercial Land',
        ProfileUpdate: 'Your profile updated',
        PasswordUpdate: 'Your password has been changed',        
        PasswordDigitError: 'Your password has been minimum 6 letters',
        AdId: 'AD ID:',
        ReportAd: 'Report this AD',
        ViewProfile: "View profile",
        Contacts: 'Contacts',
        AddReview: '+ Add Review',
        ReviewMessage: 'Your review has been updated.',
        ConfirmMobile: 'Confirm Mobiile Number',
        MobileNoError: 'Mobile number and Confirm Mobile number must be same.',
        PostMessage: 'You post has been waiting for approval',
        Add: 'Add',
        Remove: 'Remove',
        LocationError: 'Please enter your location.',
        ImageMessage: 'Maximun 5 image only can upload.',
        LinkText: 'To see the detail video about them please click the below link.',
        QuantityPickerError: 'Please select the quantity unit',
        PricePickerError: 'Please select the Price unit',
        Size: 'Size',
        RAM: 'RAM',
        Storage: 'Storage',
        Color: 'Color',
        CarParking: 'Car Parking',
        Insurance: 'Insurance',
        FuelPickerError: 'Please select Fuel type',
        TypePickerError: 'Please select Type',
        OwnerPickerError: 'Please select Owner',
        FinancePickerError: 'Please select Finance',
        InsurancePickerError: 'Please select Insurance',        
        CarPickerError: 'Please select Car parking',
        PlotPickerError: 'Please select Plot size unit',
        FacePickerError: 'Please select Facing',        
        PropertyPickerError: 'Please select Property Type',        
        BloodGroup1: 'O+',
        BloodGroup2: 'O-',
        BloodGroup3: 'A+',
        BloodGroup4: 'A-',
        BloodGroup5: 'B+',
        BloodGroup6: 'B-',
        BloodGroup7: 'AB+',
        BloodGroup8: 'AB-',
        ContactList: 'Contact List',
        TypeHere: 'Type here',
        Call: 'Call',
        Continue: 'Continue to Chat'
    },
    ta:{
        Login: 'உள்ளே நுழைய',
        Email: 'மின்னஞ்சல்',
        Password: 'கடவுச்சொல்',
        ForgotPassword: 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
        Or: 'அல்லது',
        LoginWithOTP: 'ஓடிபி உடன் உள்நுழைக',
        LoginWithFacebook: 'பேஸ்புக் மூலம் உள்நுழைக',
        LoginWithGoogle: 'கூகிள் உடன் உள்நுழைக',
        DontHaveAccount: "கணக்கு இல்லையா?",
        Signup: 'பதிவுபெறுக',
        Register: 'பதிவு',
        FirstName: 'முதல் பெயர்',
        LastName: 'கடைசி பெயர்',
        ConfirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
        Mobileno: 'கைபேசி எண்',
        Submit: 'சமர்ப்பிக்கவும்',
        EmailMobile: 'மின்னஞ்சல் அல்லது கைபேசிஎண்',
        Home: 'முகப்பு',
        Myads: 'எனதுவிளம்பரம்',
        Postad: 'புதுவிளம்பரம்',
        Chat: 'பேச',
        Profile: 'சுயவிவரம்',
        HomeHeader: "ஒன்றாக இணைவோம் ஒன்றாக உயர்வோம்",
        Search: 'தேடல்',
        Location: 'இடம்',
        CurrentLocation: 'தற்போதைய இடம்',
        //Categories
        Business: 'வணிகம்/கண்டுபிடிப்பாளர்',
        Agriculture: 'வேளாண்மை',
        Services: 'சேவைகள்',
        Gadgets: 'கைபேசி/மின்னணு',
        Electronics: 'மின் உபகரணங்கள்',
        Automobiles: 'ஆட்டோமொபைல்கள்',
        Fashion: 'ஆடை/ஃபேஷன்',
        Pets: 'செல்லப்பிராணிகள்',
        Furniture : 'பர்னிச்சர்',
        Properties: 'வீடு/நிலம்',
        Job: 'வேலைகள்',
        FreeGiveaway: 'பங்களிப்புகள்',
        //Subcategories
        Inventor1: "நான் ஒரு கண்டுபிடிப்பாளர்",
        Inventor2: "நான் ஒரு கண்டுபிடிப்பாளரைத் தேடுகிறேன்",
        Inventor3: "நான் முதலீட்டாளர் அல்லது வணிக கூட்டாளரைத் தேடுகிறேன்",
        ViewAll: "அனைத்தையும் காட்டு",
        SubAgriculture1: 'இயற்கை விவசாயம்',
        SubAgriculture2: 'காய்கறிகள்',
        SubAgriculture3: 'பழங்கள்',
        SubAgriculture4: 'பருப்பு வகைகள்/தானியங்கள்/நறுமண பொருட்கள்',
        SubAgriculture5: 'மதிப்பு கூட்டிய பொருட்கள்',
        SubAgriculture6: 'விலங்குகள்/மீன்',
        SubAgriculture7: 'தோட்டம் மற்றும் நாற்றங்கால்',
        SubAgriculture8: 'வேளாண்மை உபகரணங்கள்',        
        Others: 'மற்றவைகள்',
        SubServices1: 'காற்று குளிரூட்டும் கருவி',
        SubServices2: 'தணிக்கையாளர்',
        SubServices3: 'அழகு நிலையம்',
        SubServices4: 'கணினி & கைபேசி',
        SubServices5: 'சமையல்',
        SubServices6: 'தட்சர்',
        SubServices7: 'கட்டுமானம்',
        SubServices8: 'கார்&இரு சக்கர வாகனம் ',
        SubServices9: 'எலக்ட்ரீஷியன்',
        SubServices10: 'நிகழ்ச்சி மேலாண்மை',
        SubServices11: 'நிதி சேவைகள்',
        SubServices12: 'சுகாதாரப் பாதுகாப்பு',
        SubServices13: 'இறக்குமதி&ஏற்றுமதிt',
        SubServices14: 'தகவல் தொழில்நுட்பம்',
        SubServices15: 'சலவை',
        SubServices16: 'வழக்கறிஞர்',
        SubServices17: 'வீட்டுப் பணியாளர்',
        SubServices18: 'மூவர்ஸ்&பேக்கர்ஸ்',
        SubServices19: 'புகைப்படக் கலைஞர்',
        SubServices20: 'பிளம்பர்',
        SubServices21: 'பாதுகாப்பு காவலர்',
        SubServices22: 'பயண சேவை',
        SubServices23: 'வாடகை வண்டி',
        SubGadgets1: 'மொபைல்கள்',
        SubGadgets2: 'மடிக்கணினி&கணினி',
        SubGadgets3: 'அச்சு இயந்திரம்&பாகங்கள்',
        SubGadgets4: 'விளையாட்டுகள்&பொழுதுபோக்கு',
        SubGadgets5: 'மியூசிக் சிஸ்டம்&கேஜெட்டுகள்',
        SubGadgets6: 'உதிரி பாகங்கள்',
        SubElectronics1: 'தொலைக்காட்சி&மறைகாணி',
        SubElectronics2: 'புகைப்பட கருவி',
        SubElectronics3: 'காற்று குளிரூட்டும் கருவி',
        SubElectronics4: 'துணி துவைக்கும் இயந்திரம்&வாட்டர் ஹீட்டர்கள்',
        SubElectronics5: 'ஹவுஸ் ஹோல்ட் இயந்திரங்கள்',
        SubElectronics6: 'குளிர்சாதன பெட்டி',
        SubElectronics7: 'சமையலறை உபகரணங்கள்',
        SubAutomobiles1: 'கார்',
        SubAutomobiles2: 'இரு சக்கர வாகனம்',
        SubAutomobiles3: 'வணிகரீதியானது',
        SubFashion1: 'ஆண்கள்',
        SubFashion2: 'பெண்கள்',
        SubFashion3: 'குழந்தைகள்',
        SubPets1: 'மீன்&பறவைகள்',
        SubPets2: 'நாய்கள்&பூனைகள்/மற்ற செல்லப்பிராணிகளை',
        SubPets3: 'செல்லபிராணி உணவு&பாகங்கள்',
        SubPets4: 'தத்தெடுப்பதற்கான செல்லப்பிராணிகள்',
        Subfurniture1: 'படுக்கை&படுக்கை அறைகள்',
        Subfurniture2: 'பெட்டிகளும்&டிரஸ்ஸிங் டேபிள்',
        Subfurniture3: 'சோபா செட்&சாப்பாட்டு பெட்டிகள்',
        Subfurniture4: 'நாற்காலி&மேசை',
        Subfurniture5: 'குழந்தைகள் தளபாடங்கள்',
        Subfurniture6: 'தொலைக்காட்சி மேசை&வீட்டு அலங்காரங்கள்',
        Subfurniture7: 'அலுவலக தளபாடங்கள்',
        Subfurniture8: 'உடற்தகுதி உபகரணங்கள்',
        SubProperties1: 'விற்பனைக்கு வீடு&நிலங்கள்',
        SubProperties2: 'வாடகை வீடு&நிலங்கள்',
        SubProperties3: 'விற்பனைக்கு&வணிக வாடகை',
        Subjob1: 'கணக்கியல்',
        Subjob2: 'கட்டிடக்கலை&உட்புற வடிவமைப்பு',
        Subjob3: 'ஆட்டோமொபைல்',
        Subjob4: 'வணிக முன்னேற்றங்கள்&சந்தைப்படுத்தல்',
        Subjob5: 'கட்டுமானம்',
        Subjob6: 'வாடிக்கையாளர் சேவை',
        Subjob7: 'கல்வி',
        Subjob8: 'பொறியியல்',
        Subjob9: 'ஃபேஷன்',
        Subjob10: 'உணவு&பானங்கள்',
        Subjob11: 'கிராஃபிக் வடிவமைப்பு',
        Subjob12: 'மருத்துவமனை&சுகாதாரம்',
        Subjob13: 'மனித வளம்&நிர்வாகம்',
        Subjob14: 'தொழில்துறை&உற்பத்தி',
        Subjob15: 'தகவல் தொழில்நுட்பம்',
        Subjob16: 'சட்ட சேவைகள்',
        Subjob17: 'தளவாடங்கள்&விநியோகம்',
        Subjob18: 'சில்லறை&நுகர்வோர் பொருட்கள்',
        Subjob19: 'பாதுகாப்பு&பாதுகாப்பு',
        Subjob20: 'விற்பனை',
        Subjob21: 'போக்குவரத்து',
        Subjob22: 'பயணம்&சுற்றுலா',
        Subjob23: 'தனிப்பட்டோர்&பகுதி நேர வேலைகள்',
        SubContribution1: 'இலவசமாகக் கொடுங்கள்',
        SubContribution2: 'உங்கள் உதவி தேவை',
        //Item details
        ItemName: 'Harley Davidson Street Bob dyna',
        ItemName1: 'Pulsar 220',
        ItemLocation: 'SreeKaryam Thiruvananthapuram',
        PublishDate: '29 JUL',
        ItemInfo: '2017 - 23,500 km',
        ItemInfo1: '2014 - 53,000 km',
        //profile
        ViewEdit: 'பார்வை&சுயவிவரத்தைத் திருத்து',
        Settings: 'அமைப்புகள்',
        Support: 'ஆதரவு',
        ChangePassword: 'கடவுச்சொல்லை மாற்று',
        Share: 'பகிர்',
        Policy: 'மேலாண்மை கொள்கை',
        Logout: 'வெளியேறு',
        Notification: 'அறிவிப்புகள்',
        SelectLanguage: 'மொழியை தேர்ந்தெடுங்கள்',
        Deactivate: 'கணக்கை நீக்குக',
        NewPassword: 'புதிய கடவுச்சொல்',
        ConfirmNewPassword: 'புதிய கடவு சொல்லை உறுதி செய்',
        Favourites: 'பிடித்தவை',
        Description: 'விளக்கம்',
        PostedBy: 'விளம்பரம் பதிவிட்டவர்',
        RelatedAds: 'தொடர்புடைய விளம்பரங்கள்',
        Filter: 'வடிகட்டி',
        CusRating: 'வாடிக்கையாளர் மதிப்பீடு',
        Up: 'மேலே',
        Related: 'தொடர்புடையது',
        Date: 'தேதி',
        Distance: 'தூரம்',
        PriceHigh: 'அதிக விலை முதல் குறைந்த விலை வரை',
        PriceLow: 'குறைந்த விலை முதல் அதிக விலை வரை',
        SortBy: 'வகைபடுத்து',
        Price: 'விலை',
        Minimum: 'குறைந்தபட்சம்',
        Maximum: 'அதிகபட்சம்',
        Posted: 'பதிவிட்டவர்',
        Owner: 'உரிமையாளர்',
        Agent: 'முகவர்',
        Condition: 'நிலை',
        Old: 'பழையது',
        New: 'புதியது',
        FuelType: 'எரிபொருள் வகை',
        Petrol: 'பெட்ரோல்',
        Diesel: 'டீசல்',
        LPG: 'எல்பிஜி வாயு',
        Electric: 'மின்சார',
        Type: 'வகை',
        Manual: 'கையேடு கியர்',
        Automatic: 'தானியங்கி',
        Single: 'முதல்',
        Second: 'இரண்டாவது',
        Third: 'மூன்றாவது+',
        Model: 'மாதிரி',
        KM: 'கிலோமீட்டர்',
        Brand: 'பிராண்ட் பெயர்',
        SelectBrand: 'பிராண்டைத் தேர்ந்தெடுக்கவும்',
        AllModel: 'All Models',
        Bajaj1: 'Bajaj Avenger',
        Bajaj2: 'Bajaj CT 100',
        Bajaj3: 'Bajaj Discover',
        Bajaj4: 'Bajaj Pulsar',
        Bajaj5: 'Bajaj Platina',
        Bajaj6: 'Bajaj Others',
        Clear: 'அழி',
        Submit: 'சமர்ப்பிக்கவும்',
        SelectCategory: 'உங்கள் வகையைத் தேர்ந்தெடுக்கவும்',
        Name: 'தலைப்பு',
        SellerType: 'விற்பனையாளர் வகை',
        Next: 'அடுத்தது',
        SelectImage: 'கேலரியில் இருந்து படத்தைத் தேர்ந்தெடுக்கவும்',
        IncludeDetails: 'விவரங்களைச் சேர்க்கவும்',
        UploadImage: 'உங்கள் புகைப்படங்களை பதிவேற்றவும்',
        UploadDetails: 'உங்கள் விவரங்களைச் சமர்ப்பிக்கவும்',
        FormError: 'படிவத்தை பூர்த்தி செய்யுங்கள்',
        EmailError: 'செல்லுபடியாகும் மின்னஞ்சல் முகவரியை உள்ளிடவும்',
        PasswordError: 'கடவுச்சொல் மற்றும் உறுதிப்படுத்தும் கடவுச்சொல் ஒரே மாதிரியாக இருக்க வேண்டும்.',
        ServerError: "தரவு சேவையகத்திலிருந்து பெற முடியவில்லை",
        LogoutMSG: "நீங்கள் வெளியேறிவிட்டீர்கள்",
        ShowContact: "தொடர்பு பட்டியலைக் காட்ட இங்கே அழுத்தவும்",
        TotQuantity: "மொத்த அளவு",
        PriceInfo: "விலை தகவல்",
        Quantity: "அளவு",
        Salary: 'சம்பளம்',
        Role: 'பங்கு',
        Qualification: 'தகுதி',
        Experience: 'அனுபவம்',
        Company: 'நிறுவனத்தின் பெயர்',
        Allowance: 'கொடுப்பனவு',
        License: 'உரிமம்',
        Vacancy: 'காலியிடம்',
        PostedBy: 'பதிவிட்டவர்',
        Sale: 'விற்பனை',
        Rent: 'வாடகை',
        PlotSize: 'நில அளவு',
        Facing: 'Facing',
        BathRoom: 'குளியல் அறை',
        BedRoom: 'பெட்ரூம்',
        PropertyType: 'சொத்து வகை',
        Finance: 'நிதி',
        Update: "புதுப்பிப்பு",
        About: "என்னை பற்றி & பணி அனுபவம்",
        EditProfile: "சுயவிவரத்தைத் திருத்து",
        AboutTab: "About",
        Reviews: "விமர்சனங்கள்",
        More: "மேலும்",
        Review: "உங்கள் விமர்சனம்",
        Comment: "தங்கள் கருத்து",
        PlaceComment: "உங்கள் அனுபவத்தைப் பற்றி ஏதாவது சொல்லுங்கள்",
        NotificationInfo: "அறிவிப்புகளை அனுப்பவும் பெறவும்",
        SupportAdmin: 'நிர்வாகியுடன் இணைக்கவும்',
        Message: 'செய்தி',
        Inventor31: "ஆட்டோமொபைல்",
        Inventor32: "வேளாண்மை",
        Inventor33: "கட்டுமானம் & மனை",
        Inventor34: "கூரியர் & மூவர்ஸ்",
        Inventor35: "மின்சாரம் & மின்னணு",
        Inventor36: "ஆற்றல் & சூரிய பேனல்கள் ",
        Inventor37: "தளபாடங்கள் ",
        Inventor38: "ஹோட்டல் & காட்டேஜ் ",
        Inventor39: "உடல்நலம்",
        Inventor310: "தகவல் தொழில்நுட்பம்",
        Inventor311: "தொழில் & உற்பத்தி ",
        Inventor312: "உணவகங்கள் & பேக்கரி ",
        Inventor313: "அணிகலன்கள்",
        Inventor314: "ஜவுளி ",
        Inventor315: "பாதுகாப்பு சாதனம் ",
        SubServices24: 'திருமண ஆலோசகர்கள்',
        Privacy: 'தனியுரிமை',
        Tone: 'தொனி',
        Kg: "கிலோகிராம்",
        Bag: 'பை',
        Bunch: 'கொத்து',
        Bundle: 'மூட்டை',
        Pieces: 'துண்டுகள்',
        Permanent: 'நிரந்தர',
        Temporary: 'தற்காலிகமானது',
        House: 'வீடு',
        Appartement: 'அடுக்குமாடி இல்லங்கள்',
        Commercial: 'வணிகரீதியானது',
        East: 'கிழக்கு',
        West: 'மேற்கு',
        North: 'வடக்கு',
        South: 'தெற்கு',
        Sqft: 'சதுர அடி',
        Cent: 'சென்ட்',
        Ground: 'கிரௌண்ட்',
        Acer: 'ஏக்கர்',
        Housing: 'வீட்டு நிலம்',
        CommercialLand: 'வணிக நிலம்',
        ProfileUpdate: 'உங்கள் சுயவிவரம் புதுப்பிக்கப்பட்டது',        
        PasswordUpdate: 'உங்கள் கடவுச்சொல் மாற்றப்பட்டது',
        PasswordDigitError: 'உங்கள் கடவுச்சொல் குறைந்தபட்சம் 6 எழுத்துக்கள்',
        AdId: 'விளம்பர ஐடி:',
        ReportAd: 'இந்த விளம்பரத்தைப் புகாரளிக்கவும்',
        ViewProfile: "சுயவிவரம் காண",
        Contacts: 'தொடர்புகள்',
        AddReview: '+ மதிப்பாய்வைச் சேர்க்கவும்',
        ReviewMessage: 'உங்கள் மதிப்புரை புதுப்பிக்கப்பட்டது.',
        ConfirmMobile: 'மொபைல் எண்ணை உறுதிப்படுத்தவும்',
        MobileNoError: 'மொபைல் எண் மற்றும் உறுதிப்படுத்த மொபைல் எண் ஒரே மாதிரியாக இருக்க வேண்டும்.',
        PostMessage: 'உங்கள் விளம்பரம் ஒப்புதல்காக காத்திருக்கிறது.',
        Add: 'கூட்டு',
        Remove: 'அகற்று',
        LocationError: 'உங்கள் இருப்பிடத்தை உள்ளிடவும்.',
        ImageMessage: 'அதிகபட்சம் 5 படத்தை மட்டுமே பதிவேற்ற முடியும்.',
        LinkText: 'இந்த விளம்பரம் பற்றிய   முழு விவர வீடியே வை பார்க்க இந்த இனைப்பை அனுகவும்.',
        QuantityPickerError: 'தயவுசெய்து அளவைத் தேர்ந்தெடுக்கவும்',
        PricePickerError: 'விலையைத் தேர்ந்தெடுக்கவும்',        
        Select: 'தேர்ந்தெடுக்கவும்',
        Size: 'அளவு',
        RAM: 'ரேம்',
        Storage: 'சேமிப்பு',
        Color: 'நிறம்',
        CarParking: 'கார் பார்க்கிங்',
        Insurance: 'காப்பீடு',
        FuelPickerError: 'எரிபொருள் வகையைத் தேர்ந்தெடுக்கவும்',
        TypePickerError: 'என்ன வகை என்பதைத் தேர்ந்தெடுக்கவும்',
        OwnerPickerError: 'உரிமையாளரைத் தேர்ந்தெடுக்கவும்',
        FinancePickerError: 'பைனான்ஸ் உள்ளதா?',
        InsurancePickerError: 'காப்பீட்டைத் தேர்ந்தெடுக்கவும்',        
        CarPickerError: 'கார் நிறுத்தும் வசதி உள்ளதா',
        PlotPickerError: 'தயவு செய்து நில அளவு தேர்வு செய்யவும் ',
        FacePickerError: 'தயவு செய்து திசையை தேர்வு செய்யவும்',        
        PropertyPickerError: 'சொத்து வகையைத் தேர்ந்தெடுக்கவும்',
        SubContribution3: 'இரத்த தானம்',
        SubContribution4: 'அனாதை இல்லம் மற்றும் முதியோர் இல்லம்',
        BloodGroup1: 'ஓ+',
        BloodGroup2: 'ஓ-',
        BloodGroup3: 'ஏ+',
        BloodGroup4: 'ஏ-',
        BloodGroup5: 'பீ+',
        BloodGroup6: 'பீ-',
        BloodGroup7: 'ஏபீ+',
        BloodGroup8: 'ஏபீ-',        
        ContactList: 'தொடர்பு பட்டியல்',        
        TypeHere: 'டைப் செய்யவும்',
        HaveAccount: "ஏற்கனவே ஒரு கணக்கு உள்ளதா?",        
        Call: 'அழைப்பு',
        Continue: 'தொடர்புக்கு'
    }

})